=pod

^ Perl and LWP ^

=head1 B.4. 400s: Client Errors

If an LWP request gets any of these 400-series codes,
C<$response-E<gt>is_error> will be true, as it will be for any of the
500-series codes. For all other status codes,
C<$response-E<gt>is_error> will be false.

 400 Bad Request
 401 Unauthorized
 402 Payment Required
 403 Forbidden
 404 Not Found
 405 Method Not Allowed
 406 Not Acceptable
 407 Proxy Authentication Required
 408 Request Timeout
 409 Conflict
 410 Gone
 411 Length Required
 412 Precondition Failed
 413 Request Entity Too Large
 414 Request-URI Too Long
 415 Unsupported Media Type
 416 Requested Range Not Satisfiable
 417 Expectation Failed
 420-424: (Planned extensions involving WebDAV)
 426 Upgrade Required (RFC 2817)

=cut

#Pod::HTML2Pod conversion notes:
#From file appb_04.htm
# 1562 bytes of input
#Sun Nov 11 18:09:49 2012 root
# No a_name switch not specified, so will not try to render <a name='...'>
# Will try to render <a href='...'>
# Untranslatable link: "./index.html"
