=pod

^ Perl and LWP ^

=head1 Appendix C. Common MIME Types

Every HTTP response that's more than just headers must specify a MIME
type via the C<Content-Type> header (accessible as
C<$response-E<gt>content_type( )>). Here is a list of the usual MIME
type for each of the most common file types on the Internet. The items
are sorted alphabetically by the usual extensions.

Regrettably, this list is neither complete nor authoritative, as there
are more file types in use than those given "official" MIME types. For
more information, see I<HTTP: The Definitive Guide> (O'Reilly). Also
consider the I<mime.types> file that comes with Apache and/or your
browser's "Helper Applications" configuration menus. For the list of
official MIME types, see
http://www.isi.edu/in-notes/iana/assignments/media-types/
(http://www.isi.edu/in-notes/iana/assignments/media-types/).

Extension

MIME type

I<.au>

C<audio/basic>

I<.avi>

C<video/msvideo, video/avi, video/x-msvideo>

I<.bmp>

C<image/bmp>

I<.bz2>

C<application/x-bzip2>

I<.css>

C<text/css>

I<.dtd>

C<application/xml-dtd>

I<.doc>

C<application/msword>

I<.exe>

C<application/octet-stream>

I<.gif>

C<image/gif>

I<.gz>

C<application/x-gzip>

I<.hqx>

C<application/mac-binhex40>

I<.html>

C<text/html>

I<.jar>

C<application/java-archive>

I<.jpg>

C<image/jpeg>

I<.js>

C<application/x-javascript>

I<.midi>

C<audio/x-midi>

I<.mp3>

C<audio/mpeg>

I<.mpeg>

C<video/mpeg>

I<.ogg>

C<audio/vorbis, application/ogg>

I<.pdf>

C<application/pdf>

I<.pl>

C<application/x-perl>

I<.png>

C<image/png>

I<.ppt>

C<application/vnd.ms-powerpoint>

I<.ps>

C<application/postscript>

I<.qt>

C<video/quicktime>

I<.ra>

C<audio/x-pn-realaudio, audio/vnd.rn-realaudio>

I<.ram>

C<audio/x-pn-realaudio, audio/vnd.rn-realaudio>

I<.rdf>

C<application/rdf, application/rdf+xml>

I<.rtf>

C<application/rtf>

I<.sgml>

C<text/sgml>

I<.sit>

C<application/x-stuffit>

I<.svg>

C<image/svg+xml>

I<.swf>

C<application/x-shockwave-flash>

I<.tar.gz>

C<application/x-tar>

I<.tgz>

C<application/x-tar>

I<.tiff>

C<image/tiff>

I<.tsv>

C<text/tab-separated-values>

I<.txt>

C<text/plain>

I<.wav>

C<audio/wav, audio/x-wav>

I<.xls>

C<application/vnd.ms-excel>

I<.xml>

C<application/xml>

I<.zip>

C<application/zip, application/x-compressed-zip>

=cut

#Pod::HTML2Pod conversion notes:
#From file appc_01.htm
# 6717 bytes of input
#Sun Nov 11 18:09:49 2012 root
# No a_name switch not specified, so will not try to render <a name='...'>
# Will try to render <a href='...'>
# Untranslatable link: "./index.html"
