=pod

^ Perl and LWP ^

=head1 0.6. Comments & Questions

Please address comments and questions concerning this book to the
publisher:

=over

O'Reilly & Associates, Inc.

1005 Gravenstein Highway North

Sebastopol, CA 95472

(800) 998-9938 (in the United States or Canada)

(707) 829-0515 (international/local)

(707) 829-0104 (fax)

=back

There is a web page for this book, which lists errata, examples, or any
additional information. You can access this page at:

=over

http://www.oreilly.com/catalog/perllwp/
(http://www.oreilly.com/catalog/perllwp/)

=back

To comment or ask technical questions about this book, send email to:

=over

bookquestions@oreilly.com (mailto:bookquestions@oreilly.com)

=back

For more information about books, conferences, Resource Centers, and
the O'Reilly Network, see the O'Reilly web site at:

=over

http://www.oreilly.com (http://www.oreilly.com)

=back

=cut

#Pod::HTML2Pod conversion notes:
#From file ch00_06.htm
# 1832 bytes of input
#Sun Nov 11 18:10:04 2012 root
# No a_name switch not specified, so will not try to render <a name='...'>
# Will try to render <a href='...'>
# Untranslatable link: "./index.html"
