=pod

^ Perl and LWP ^

=head1 0.3. Order of Chapters

The chapters in this book are arranged so that if you read them in
order, you will face a minimum of cases where I have to say "you won't
understand this part of the code, because we won't cover that topic
until two chapters later." However, only some of what each chapter
introduces is used in later chapters. For example, Chapter 3, "The LWP
Class Model" lists all sorts of LWP methods that you are likely to use
eventually, but the typical task will use only a few of those, and only
a few will show up in later chapters. In cases where you can't infer
the meaning of a method from its name, you can always refer back to the
earlier chapters or use C<perldoc> to see the applicable module's
online reference documentation.

=cut

#Pod::HTML2Pod conversion notes:
#From file ch00_03.htm
# 1514 bytes of input
#Sun Nov 11 18:10:04 2012 root
# No a_name switch not specified, so will not try to render <a name='...'>
# Will try to render <a href='...'>
# Untranslatable link: "./index.html"
# Untranslatable link: "ch03_01.htm"
